[package]
name = "filecoin-rs"
version = "0.1.0"
edition = "2021"
authors = ["Joshua Head <support@jeldonmusic.com>"]
description = "Filecoin integrations with Tauri UI"
repository = "https://github.com/jhead12"
license = "MIT"

[lib]
crate-type = ["cdylib", "rlib"]
path = "src/lib.rs"

[[bin]]
name = "filecoin-rs"
path = "src/main.rs"
required-features = ["native"]

[dependencies]
cid = "0.11.1"
multihash-codetable = { version = "0.1.4", features = ["sha2"] }
anyhow = "1.0"
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4" # For async support
getrandom = { version = "0.2", features = ["js"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
console_log = "1.0" # For console logging
log = "0.4" # For log::Level
opentelemetry-datadog = "0.17.0"
# Tauri dependencies (all optional)
tauri = { version = "2.3.1", optional = true }
tauri-plugin-window-state = { version = "2.0.0", optional = true }
tauri-plugin-upload = { version = "2.0.0", optional = true }
tauri-plugin-shell = { version = "2.0.0", optional = true }
tauri-plugin-opener = { version = "2.0.0", optional = true }
tauri-plugin-log = { version = "2.0.0", optional = true }
# Filecoin dependencies (optional for native builds)
fvm_ipld_blockstore = { version = "0.3.1", optional = true }
fvm = { version = "4.6.0", optional = true }
fvm_shared = { version = "4.6.0", optional = true }
fvm_ipld_encoding = { version = "0.5.2", optional = true }
positioned-io = { version = "0.3", optional = true }

[features]
# Default feature is empty for WASM compatibility
default = []
fvm_ipld_blockstore = ["dep:fvm_ipld_blockstore"]
# Native feature enables Tauri and Filecoin dependencies
# native = [
#     "tauri",
#     "tauri-plugin-window-state",
#     "tauri-plugin-upload",
#     "tauri-plugin-shell",
#     "tauri-plugin-opener",
#     "tauri-plugin-log",
#     "fvm_ipld_blockstore",
#     "fvm",
#     "fvm_shared",
#     "fvm_ipld_encoding",
#     "positioned-io"
# ]

[profile.dev]
opt-level = 0
debug = true
split-debuginfo = "unpacked"
strip = "none"
debug-assertions = true
overflow-checks = true
lto = false
panic = "unwind"
incremental = true
codegen-units = 256
rpath = false

[profile.release]
opt-level = 3
